packages:
  - "packages/*"

catalog:
  # =======================================================================
  # >> Common/Workspace Dependencies
  # =======================================================================
  # Core & Tooling
  "@types/node": "20.2.5"
  "tslib": "^2.8.1"
  "typescript": "~5.7.2"
  "turbo": "^2.3.3"
  "husky": "^9.1.6"

  # Shared Build Tools
  "rollup": "~4.29.1"
  "@rollup/plugin-typescript": "~12.1.2"

  # =======================================================================
  # >> Commit & Changelog
  # =======================================================================
  "czg": ^1.10.1
  "cz-git": ^1.10.1
  "@changesets/cli": "~2.27.7"
  "@commitlint/cli": "^19.5.0"
  "@commitlint/config-conventional": "^19.5.0"
  "commitlint-plugin-function-rules": "^4.0.1"
  "@quantum-design-configs/commitlint": "^1.0.2"

  # =======================================================================
  # >> Linting & Formatting
  # =======================================================================
  "lint-staged": "^15.2.10"
  "@typescript-eslint/eslint-plugin": "~8.18.2"
  "@typescript-eslint/parser": "~8.18.2"
  "eslint-config-turbo": "~2.3.3"
  "eslint-plugin-vue": "~9.32.0"
  "eslint": "~8.57.0"
  "@quantum-design-configs/eslint": "^2.0.0"

  # =======================================================================
  # >> mini-vue Dependencies
  # =======================================================================
  "@rollup/plugin-commonjs": "~28.0.2"
  "@rollup/plugin-node-resolve": "~16.0.0"

  # =======================================================================
  # >> mini-vite Dependencies
  # =======================================================================
  "cac": "^6.7.14"
  "chokidar": "^3.5.3"
  "connect": "^3.7.0"
  "debug": "^4.3.4"
  "es-module-lexer": "^1.1.0"
  "esbuild": "^0.15.15"
  "fs-extra": "~11.2.0"
  "@types/fs-extra": "~11.0.4" # Belongs to fs-extra
  "magic-string": "^0.26.7"
  "picocolors": "^1.0.0"
  "resolve": "^1.22.1"
  "sirv": "^2.0.2"
  "vue": "^3.3.12"
  "ws": "^8.11.0"
  "npm-run-all2": "^6.1.1"
  "rimraf": "^3.0.2"
  "@types/connect": "^3.4.38"
  "@types/debug": "^4.1.12"
  "@types/resolve": "^1.20.6"
  "@types/ws": "^8.11.0"
  # =======================================================================
  # >> Uncategorized / Potentially Unused
  # =======================================================================
  "@rollup/plugin-terser": "~0.4.4"
  "@rollup/plugin-json": "~6.1.0"
  "lodash-es": "~4.17.21"
  "@types/lodash-es": "~4.17.12"
  "cross-env": "~7.0.3"
  "esno": "~0.17.0"
  "openai": "~4.86.1"
  "kolorist": "^1.8.0"
  "minimist": "^1.2.5"
  "prompts": "^2.4.2"
  "unbuild": "^2.0.0"
  "zod": "^3.24.2"
  "@modelcontextprotocol/sdk": "^1.8.0"
  "dotenv": "^16.4.5"
  "express": "^5.0.1"
  "pinia": "^3.0.1"